{
 "title": "EH",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "label": "DS", "query": "prometheus" },
   { "name": "user", "label": "User", "query": { "query": "label_values(user)" } }
  ]
 },
 "panels": [
  {
   "title": "Account",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "EHT down/up",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "eh_eht_uploaded_mb{user=\"$user\"}",
       "legendFormat": "Up"
      },
      {
       "expr": "eh_eht_downloaded_mb{user=\"$user\"}",
       "legendFormat": "Down"
      }
     ]
    },
    {
     "title": "EHT seeding",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "expr": "eh_eht_seed_minutes{user=\"$user\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total GP Gained",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "GP" } },
     "targets": [
      {
       "expr": "eh_gp_gained_number{user=\"3565237\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "EHT completes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eh_eht_completes_number{user=\"$user\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "HatH balance",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "eh_hath_balance_number{user=\"$user\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Real clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Transfer bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (eh_hath_transfer_tx_bytes{user=\"$user\"})",
     "legendFormat": "TX: {{name}}"
    },
    {
     "expr": "sum by(name) (eh_hath_transfer_rx_bytes{user=\"$user\"})",
     "legendFormat": "RX: {{name}}"
    }
   ]
  },
  {
   "title": "Transfer files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(name) (eh_hath_transfer_tx_files_count{user=\"$user\"})",
     "legendFormat": "TX: {{name}}"
    },
    {
     "expr": "sum by(name) (eh_hath_transfer_rx_files_count{user=\"$user\"})",
     "legendFormat": "RX: {{name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (eh_hath_client_uptime_seconds{user=\"$user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "targets": [
    {
     "expr": "sum by(name) (eh_hath_client_status{user=\"$user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(name) (eh_hath_connections_open_count{user=\"$user\"})",
     "legendFormat": "Curr: {{name}}"
    },
    {
     "expr": "sum by(name) (eh_hath_connections_max_count{user=\"$user\"})",
     "legendFormat": "Limit: {{name}}"
    }
   ]
  },
  {
   "title": "Cache files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum by(name) (eh_hath_cache_file_count{user=\"$user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(name) (eh_hath_cache_size_limit_bytes{user=\"$user\"})",
     "legendFormat": "Limit: {{name}}"
    },
    {
     "expr": "avg by(name) (eh_hath_cache_size_bytes{user=\"$user\"})",
     "legendFormat": "Current: {{name}}"
    }
   ]
  },
  { "title": "H@H Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg by(client_name) (eh_hath_clients_quality_number{user=\"$user\"})",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Trust",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by(client_name) (eh_hath_clients_trust_number{user=\"$user\"})",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Clients status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 15 },
   "targets": [
    {
     "expr": "sum by(client_name) (eh_hath_clients_status_enum{user=\"$user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total hit/m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h/m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eh_hath_clients_hitrate_number{user=\"$user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Files served",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(client_name) (eh_hath_clients_files_served_number{user=\"$user\"})",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Max speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum by(client_name) (eh_hath_clients_max_speed_kbps{user=\"$user\"})",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Total hath/day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "H/D" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eh_hath_clients_hathrate_number{user=\"$user\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total static ranges",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eh_hath_clients_ranges_number{user=\"$user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "H@H Regions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "H@H Hits/GB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avg by(region) (eh_hath_regions_hits_per_gb_ratio{user=\"$user\"})",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "H@H Quality",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "avg by(region) (eh_hath_regions_quality_number{user=\"$user\"})",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "H@H Coverage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(region) (eh_hath_regions_coverage_percent{user=\"$user\"})",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "H@H hits/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(region) (eh_hath_regions_hits_per_second_ratio{user=\"$user\"})",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "H@H Net Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "avg by(region) (eh_hath_regions_netload_mbps{user=\"$user\"})",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, name) (rate(eh_job_run_time_seconds_bucket{user=\"$user\"}[1h])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "eh_job_failures_number{user=\"$user\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Clients status",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 2, "x": 22, "y": 45 },
     "targets": [
      {
       "expr": "sum by(client_name) (eh_app_version_state{user=\"$user\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}