services:
  sdhub:
    image: ${REGISTRY-local}/${IMAGE_NAME-ehmetrics}:${IMAGE_TAG-latest}
    build:
      context: ../
      network: host
      target: app
      dockerfile: ./docker/Dockerfile
      args:
        - GIT_REF
        - GIT_REF_TYPE
        - GIT_COMMIT_SHA
        - PROJECT_URL
        - REPO_URL