services:
  eh-metrics:
    image: ghcr.io/mixa3607/eh_metrics:v1.0.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./appsettings.json:/homes/app/appsettings.Production.json:ro
    ports:
      - 80:8080
    restart: unless-stopped
