name: build-container
on:
  push:
    branches:
      - '*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository.toLowerCase() }}
  IMAGE_TAG1: ${{ github.ref_name.toLowerCase() }}
  IMAGE_TAG2: ${{ github.sha.toLowerCase() }}
  GIT_REF: ${{ github.ref_name }}
  GIT_REF_TYPE: ${{ github.ref_type }}
  GIT_COMMIT_SHA: ${{ github.sha }}
  REPO: "${{ github.repository }}"
  PROJECT_URL: ${{ github.server_url }}/${{ github.repository }}
  REPO_URL: ${{ github.repositoryUrl }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
            docker compose --env-file ./docker/build.env config
            export IMAGE_TAG=TMP
            docker compose --env-file ./docker/build.env build
      - name: Push
        run: |
          docker tag $REGISTRY/$IMAGE_NAME:TMP $REGISTRY/$IMAGE_NAME:$IMAGE_TAG1
          docker tag $REGISTRY/$IMAGE_NAME:TMP $REGISTRY/$IMAGE_NAME:$IMAGE_TAG2
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG1
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG2
