name: push_version_tag
on:
  push:
    tags:        
      - v*
env:
  REGISTRY: ghcr.io
  GIT_REF: ${{ github.ref_name }}
  GIT_REF_TYPE: ${{ github.ref_type }}
  GIT_COMMIT_SHA: ${{ github.sha }}
  REPO: "${{ github.repository }}"
  PROJECT_URL: ${{ github.server_url }}/${{ github.repository }}
  REPO_URL: ${{ github.repositoryUrl }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: env vars
        run: |
          echo "IMAGE_NAME=${REPO,,}"             >> ${GITHUB_ENV}
          echo "IMAGE_TAG=${GIT_REF,,}"           >> ${GITHUB_ENV}
        env:
          GIT_REF: ${{ github.ref_name }}
          REPO: "${{ github.repository }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
            export COMPOSE_FILE=./docker/build.yml
            docker compose config
            docker compose build
      - name: Push
        run: docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
